databaseChangeLog:
  - changeSet:
      id: 000-1
      author: Anton
      changes:
        - createTable:
            tableName: wallet
            columns:
              - column:
                  name: UUID
                  type: varchar
                  constraints:
                    primaryKey: true
                    nullable: false
              - column:
                  name: balance
                  type: real
              - column:
                  name: full_name
                  type: varchar