version: '3.8'
services:
  postgres-db:
    image: postgres:16
    restart: always
    env_file:
      - .env
    volumes:
      - .\database:/var/lib/postgresql/data
    ports:
      - 5001:5432

  liquibase:
    image: liquibase/liquibase:4.26.0
    depends_on:
      - postgres-db
    volumes:
      - .\db\changelog\changesets:/liquibase/changelog/
    command: --changelog-file=./db/changelog/changesets/db.changelog-master.yaml --url=jdbc:postgresql://postgres-db/wallet --username=postgres --password=postgres update

  app:
    image: client:0.0.1
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db/wallet
    ports:
      - 8008:8080
    depends_on:
      - postgres-db

networks:
  default:
    external:
      name: test-net